# Generated by Django 3.1.5 on 2021-01-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='closing_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
